# Generated by Django 4.2.21 on 2025-05-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('auto_labeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autolabelingconfig',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_labeling_config', to='projects.project'),
        ),
    ]
