# Generated by Django 4.2.21 on 2025-06-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperspective',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='userperspective',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perspective',
        ),
        migrations.DeleteModel(
            name='UserPerspective',
        ),
    ]
