# Generated by Django 4.2.20 on 2025-05-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='selection_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_perspective_mappings', to='projects.perspective')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
