# Generated by Django 4.2.21 on 2025-06-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_userperspective_perspective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationrule',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotationrule',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
