# Generated by Django 4.2.15 on 2025-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="agreementPercentage",
            field=models.FloatField(default=50.0),
        ),
    ]
