# Generated by Django 4.2.15 on 2025-04-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_agreementpercentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="agreementPercentage",
            new_name="agreement_percentage",
        ),
    ]
