# Generated by Django 4.2.15 on 2025-06-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perspectives", "0003_initial"),
        ("projects", "0012_ticket_ticketcomment_delete_rulecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="perspective",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="perspectives.perspective"
            ),
        ),
    ]
