# Generated by Django 4.2.15 on 2025-06-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_project_perspective"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationrule",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotationrule",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotationrule",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
