# Generated by Django 4.2.15 on 2025-03-29 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerspectiveType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project")),
            ],
            options={
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                (
                    "perspectivetype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="perspective_types.perspectivetype",
                    ),
                ),
            ],
            bases=("perspective_types.perspectivetype",),
        ),
        migrations.CreateModel(
            name="RelationType",
            fields=[
                (
                    "perspectivetype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="perspective_types.perspectivetype",
                    ),
                ),
            ],
            bases=("perspective_types.perspectivetype",),
        ),
        migrations.CreateModel(
            name="SpanType",
            fields=[
                (
                    "perspectivetype_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="perspective_types.perspectivetype",
                    ),
                ),
            ],
            bases=("perspective_types.perspectivetype",),
        ),
        migrations.CreateModel(
            name="PerspectiveItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "perspective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="perspective_types.perspectivetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("perspective", "name")},
            },
        ),
    ]
