# Generated by Django 4.2.15 on 2025-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0008_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
