# Generated by Django 4.2.15 on 2025-06-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perspectives", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itemvalue",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="itemvalue",
            name="item",
        ),
        migrations.AlterUniqueTogether(
            name="value",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="value",
            name="example",
        ),
        migrations.RemoveField(
            model_name="value",
            name="item",
        ),
        migrations.RemoveField(
            model_name="value",
            name="item_value",
        ),
        migrations.RemoveField(
            model_name="value",
            name="user",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="ItemValue",
        ),
        migrations.DeleteModel(
            name="Value",
        ),
    ]
