# Generated by Django 4.2.21 on 2025-05-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perspectives', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.member'),
        ),
        migrations.AddField(
            model_name='value',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspectives.perspective'),
        ),
        migrations.AddField(
            model_name='perspective',
            name='items',
            field=models.ManyToManyField(to='perspectives.item'),
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('member', 'item')},
        ),
    ]
