# Generated by Django 4.2.21 on 2025-05-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perspectives', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.member'),
        ),
        migrations.AddField(
            model_name='itemvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_values', to='perspectives.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_items', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('member', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='itemvalue',
            unique_together={('item', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('project', 'name')},
        ),
    ]
