# Generated by Django 4.2.15 on 2025-06-12 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0012_ticket_ticketcomment_delete_rulecomment"),
        ("perspectives", "0002_alter_itemvalue_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("selection_list", models.JSONField(blank=True, default=list)),
                ("item_type", models.CharField(default="string", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Perspective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("items", models.ManyToManyField(to="perspectives.item")),
            ],
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.TextField()),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="perspectives.item")),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.member")),
                (
                    "perspective",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="perspectives.perspective"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("member", "item")},
            },
        ),
    ]
